jenkins: 
    build: ./jenkins 
    volumes: 
      - /Users/guillermohurtado/Desktop/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/local/bin/docker:/usr/bin/docker 
    ports:
      - 8080:8080
      - 50000:50000 
    environment: 
      DOCKER_SOCKET: /var/run/docker.sock 
      DOCKER_GROUP: dockerhost 
      JENKINS_USER: jenkins 
      JENKINS_URL: "https://jenkins.example.com/" 
      DOCKER_HOST: unix:///var/run/docker.sock 
